# Generated by Django 5.0.6 on 2024-07-07 06:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('sofascore_id', models.IntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sofascore_id', models.IntegerField(unique=True)),
                ('nombre', models.CharField(max_length=255)),
                ('nacionalidad', models.CharField(max_length=255)),
                ('posicion', models.CharField(max_length=50)),
                ('fecha_nacimiento', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Torneo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('sofascore_id', models.IntegerField(unique=True)),
                ('nombre_temporada', models.CharField(max_length=255)),
                ('año_temporada', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Partido',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('id_sofascore_evento', models.IntegerField(unique=True)),
                ('ronda', models.CharField(max_length=255)),
                ('estado', models.CharField(max_length=255)),
                ('puntuacion_local', models.IntegerField()),
                ('puntuacion_visitante', models.IntegerField()),
                ('goles_tiempo_normal_local', models.IntegerField()),
                ('goles_tiempo_normal_visitante', models.IntegerField()),
                ('comienzo_periodo_actual', models.DateTimeField()),
                ('inicio_partido', models.DateTimeField()),
                ('equipo_local', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partidos_local', to='stats.equipo')),
                ('equipo_visitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partidos_visitante', to='stats.equipo')),
                ('torneo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stats.torneo')),
            ],
        ),
        migrations.CreateModel(
            name='FbrefStatsJugador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_camiseta', models.IntegerField()),
                ('Min', models.IntegerField()),
                ('Gls', models.IntegerField()),
                ('Ast', models.IntegerField()),
                ('Sh', models.IntegerField()),
                ('SoT', models.IntegerField()),
                ('CrdY', models.IntegerField()),
                ('CrdR', models.IntegerField()),
                ('Fls', models.IntegerField()),
                ('Fld', models.IntegerField()),
                ('Off', models.IntegerField()),
                ('Crs', models.IntegerField()),
                ('TklW', models.IntegerField()),
                ('Int', models.IntegerField()),
                ('OG', models.IntegerField()),
                ('PKatt', models.IntegerField()),
                ('PKwon', models.IntegerField()),
                ('PK', models.IntegerField()),
                ('PKcon', models.IntegerField()),
                ('Pos', models.CharField(max_length=10)),
                ('edad_dia_partido', models.CharField(max_length=20)),
                ('nation', models.CharField(max_length=10)),
                ('fbref_player_id', models.CharField(max_length=100)),
                ('partido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stats.partido')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stats.player')),
            ],
        ),
        migrations.CreateModel(
            name='SofascoreStatsJugador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_camiseta', models.IntegerField()),
                ('suplente', models.BooleanField()),
                ('total_pases', models.IntegerField()),
                ('pases_precisos', models.IntegerField()),
                ('total_balones_en_largo', models.IntegerField()),
                ('balones_en_largo_completados', models.IntegerField()),
                ('total_centros', models.IntegerField()),
                ('centros_completados', models.IntegerField()),
                ('duelos_aereos_perdidos', models.IntegerField()),
                ('duelos_aereos_ganados', models.IntegerField()),
                ('minutos_jugados', models.IntegerField()),
                ('duelos_perdidos', models.IntegerField()),
                ('duelos_ganados', models.IntegerField()),
                ('tiros_fuera', models.IntegerField()),
                ('tiros_dentro', models.IntegerField()),
                ('goles', models.IntegerField()),
                ('sofascore_rating', models.FloatField()),
                ('partido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stats.partido')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stats.player')),
            ],
        ),
    ]
