# Generated by Django 5.0.6 on 2024-07-07 17:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeatMapPlayerMatch',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('heatmap', models.JSONField()),
                ('partido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stats.partido')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stats.player')),
            ],
        ),
        migrations.CreateModel(
            name='ManagerTeamPartido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manager_sofascore_id', models.IntegerField()),
                ('manager_name', models.CharField(max_length=255)),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stats.equipo')),
                ('partido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stats.partido')),
            ],
        ),
    ]
