# Generated by Django 5.0.6 on 2024-07-20 17:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0003_sofascorestatsjugador_accurate_keeper_sweeper_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sofascorestatsjugador',
            name='equipo',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='stats.equipo'),
        ),
    ]
