# Generated by Django 5.0.6 on 2024-07-23 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0005_alter_player_fecha_nacimiento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fbrefstatsjugador',
            name='Ast',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fbrefstatsjugador',
            name='CrdR',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fbrefstatsjugador',
            name='CrdY',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fbrefstatsjugador',
            name='Crs',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fbrefstatsjugador',
            name='Fld',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fbrefstatsjugador',
            name='Fls',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fbrefstatsjugador',
            name='Gls',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fbrefstatsjugador',
            name='Int',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fbrefstatsjugador',
            name='Min',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fbrefstatsjugador',
            name='OG',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fbrefstatsjugador',
            name='Off',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fbrefstatsjugador',
            name='PK',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fbrefstatsjugador',
            name='PKatt',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fbrefstatsjugador',
            name='PKcon',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fbrefstatsjugador',
            name='PKwon',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fbrefstatsjugador',
            name='Pos',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='fbrefstatsjugador',
            name='Sh',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fbrefstatsjugador',
            name='SoT',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fbrefstatsjugador',
            name='TklW',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fbrefstatsjugador',
            name='edad_dia_partido',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='fbrefstatsjugador',
            name='fbref_player_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='fbrefstatsjugador',
            name='nation',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='fbrefstatsjugador',
            name='numero_camiseta',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
